"""empty message

Revision ID: 6036e706a8f5
Revises: 
Create Date: 2020-03-27 09:10:43.737455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6036e706a8f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
